#! /bin/bash

#default: get vimrc from machine
#if $1=set => set vimrc in machine

continue=0
if [ "$1" == "set" ]; then
    echo "***diff vimrc ~/.vimrc"
    diff vimrc ~/.vimrc
    echo "**********************"
    echo "diff files between vim/ ~/.vim"
    diff -r vim ~/.vim
    echo "******************************"
    while [ $continue -eq 0 ];do
        read -p "delete $HOME/.vimrc $HOME/.vim?[y/n]" answer
        if [ "$answer" == "y" ]; then
            continue=1
            mkdir save_tmp
            mv ~/.vimrc ~/.vim save_tmp
            cp vimrc $HOME/.vimrc
            cp -r vim $HOME/.vim
        elif [ "$answer" == "n" ]; then
            continue=1
        else
            continue=0
        fi
    done
else
    echo "***diff vimrc ~/.vimrc"
    diff ~/.vimrc vimrc 
    echo "**********************"
    echo "diff files between vim/ ~/.vim"
    diff -r ~/.vim vim
    echo "******************************"
    while [ $continue -eq 0 ];do
        read -p "get $HOME/.vimrc $HOME/.vim?[y/n]" answer
        if [ "$answer" == "y" ]; then
            continue=1
            cp ~/.vimrc vimrc
            cp -r ~/.vim vim
        elif [ "$answer" == "n" ]; then
            continue=1
        else
            continue=0
        fi
    done
fi
